### ISSUE TITLE
Tab Bar 消失

### ISSUE THREAD

**Issue by sunnyleeyun** [madcrew-taiwan/GitHub-Practice-Zebra#1]
設定 > 更新個人資料 > 完成
tab bar三個不見
就只能登出了

**Comment by KennyLee-Taiwan** [comment]
@sunnyleeyun 

確實是個 Bug 呢！已修正囉！感謝 Sunny～～

![1](https://cloud.githubusercontent.com/assets/16862749/19659979/a742bd34-9a60-11e6-92b7-10509c47cbec.png)
![2](https://cloud.githubusercontent.com/assets/16862749/19659981/a7687b46-9a60-11e6-881f-efba8095cf48.png)
![3](https://cloud.githubusercontent.com/assets/16862749/19659982/a779ee8a-9a60-11e6-9fa4-3ffe26df9a78.png)
