### ISSUE TITLE
Pop Up View 背景

### ISSUE THREAD

**Issue by sunnyleeyun** [madcrew-taiwan/GitHub-Practice-Zebra#2]
地圖 > 人Button > pop up view
其中的pop up view的背景可以變成模糊或其他方式
背景變全黑似乎有點唐突

**Comment by KennyLee-Taiwan** [comment]
@sunnyleeyun 

現在的版本看起來有像妳提到的 Clash Royale 那種感覺，加上現在 #3 的新設計，妳看看還會不會有唐突的感覺，有的話趕緊提出唷！

![default](https://cloud.githubusercontent.com/assets/16862749/19660213/72d88636-9a61-11e6-8b2f-968da8a07238.png)
![default](https://cloud.githubusercontent.com/assets/16862749/19660214/72db3138-9a61-11e6-80f2-fed3c721b573.jpg)

**Comment by KennyLee-Taiwan** [comment]
感謝各位提供之各種 UI 設計的建議＋臭蟲回報！目前的建議都已經改上去了！通常狀況我們一定會改到大家都 100% 滿意再開始實作，但實在因為黑客松在即，我們就以目前最新版的 UI 正式開始開發囉！要是還有什麼 UI 的改動建議，就留到週末黑客松，整個專案都完成並 Merge 成一個確定最終版後，大家再在同一台機器上一次改囉！
