### ISSUE TITLE
遞名片功能

### ISSUE THREAD

**Issue by sunnyleeyun** [madcrew-taiwan/GitHub-Practice-Zebra#3]
之前好像有說一個「遞名片」的按鈕
是version 2之類的才要做嗎？
覺得這個功能蠻酷的
應該也不會很難做

**Comment by Robert0321** [comment]
我剛剛把你說的這些調整，有名片的感覺了!!!!
只是我想說整體介面有名片的feel，可以不需要在用一個「遞名片」的按鈕，去強調它。
PS:背後透明喔~~~~~
這是使用者易視性的概念。
![14795956_10210476808573731_422072701_o](https://cloud.githubusercontent.com/assets/23011869/19649343/126b1d46-9a38-11e6-8991-553f11209570.jpg)

**Comment by KennyLee-Taiwan** [comment]
感謝各位提供之各種 UI 設計的建議＋臭蟲回報！目前的建議都已經改上去了！通常狀況我們一定會改到大家都 100% 滿意再開始實作，但實在因為黑客松在即，我們就以目前最新版的 UI 正式開始開發囉！要是還有什麼 UI 的改動建議，就留到週末黑客松，整個專案都完成並 Merge 成一個確定最終版後，大家再在同一台機器上一次改囉！
