### ISSUE TITLE
註冊

### ISSUE THREAD

**Issue by sunnyleeyun** [madcrew-taiwan/GitHub-Practice-Zebra#5]
註冊那邊是還沒弄好嗎
因為除了職業其他按鈕目前都沒下一步
此外選職業的Label「尚未選取」可否置中

**Comment by Robert0321** [comment]
@sunnyleeyun 
職業的部分，我把「尚未選取」放在資料夾上。
![14813205_10210476965217647_909403263_o](https://cloud.githubusercontent.com/assets/23011869/19649227/96cbf32c-9a37-11e6-84b9-1938fafdc98a.jpg)

**Comment by KennyLee-Taiwan** [comment]
@sunnyleeyun 

因為其他按鈕之後想要做成像下圖那樣，不過因為要用 Code 實現這樣的功能，所以現在點下去就暫時沒效果囉！

![popup](https://cloud.githubusercontent.com/assets/16862749/19660360/0703f926-9a62-11e6-808e-ca2c90e70603.png)

**Comment by KennyLee-Taiwan** [comment]
感謝各位提供之各種 UI 設計的建議＋臭蟲回報！目前的建議都已經改上去了！通常狀況我們一定會改到大家都 100% 滿意再開始實作，但實在因為黑客松在即，我們就以目前最新版的 UI 正式開始開發囉！要是還有什麼 UI 的改動建議，就留到週末黑客松，整個專案都完成並 Merge 成一個確定最終版後，大家再在同一台機器上一次改囉！
