### ISSUE TITLE
交流紀錄

### ISSUE THREAD

**Issue by sunnyleeyun** [madcrew-taiwan/GitHub-Practice-Zebra#6]
交流紀錄
按進去之後上面有一個白白的view是什麼用途

**Comment by KennyLee-Taiwan** [comment]
@sunnyleeyun 

那是...個 Bug :p  應該要是一條筆記的，已修正！！！

![screen shot 2016-10-25 at 3 23 45 am](https://cloud.githubusercontent.com/assets/16862749/19660460/756bc074-9a62-11e6-882d-50781d2cd30f.png)
