### ISSUE TITLE
交流Button的返回VC

### ISSUE THREAD

**Issue by sunnyleeyun** [madcrew-taiwan/GitHub-Practice-Zebra#8]
地圖 > pop up view > 交流button >  聊天對話框
if 要跟line一樣，navigation的back應該是要回到「交流紀錄」的那一頁，現在是回到pop up view

**Comment by KennyLee-Taiwan** [comment]
@sunnyleeyun 

因為使用者可能 Pop up view 上面的資訊還沒有讀完，就按到聊天鍵，如果按返回會回到「交流紀錄」的話，就找不到剛剛還沒有讀完的 pop up view 了。 如果是從 交流紀錄 -> 聊天對話框 -> 返回 的話，就會回到「交流紀錄」了唷！

![screen shot 2016-10-25 at 3 34 03 am](https://cloud.githubusercontent.com/assets/16862749/19660815/eb5fc0cc-9a63-11e6-92bc-2c527e08666c.png)
![screen shot 2016-10-25 at 3 34 09 am](https://cloud.githubusercontent.com/assets/16862749/19660816/eb5fdfda-9a63-11e6-9012-5f7c68cb3e87.png)

**Comment by KennyLee-Taiwan** [comment]
感謝各位提供之各種 UI 設計的建議＋臭蟲回報！目前的建議都已經改上去了！通常狀況我們一定會改到大家都 100% 滿意再開始實作，但實在因為黑客松在即，我們就以目前最新版的 UI 正式開始開發囉！要是還有什麼 UI 的改動建議，就留到週末黑客松，整個專案都完成並 Merge 成一個確定最終版後，大家再在同一台機器上一次改囉！
